version: '2'

services:
  db:
    container_name: mysticpaste_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: mysticpaste
