version: '2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: mysticpaste
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/kinabalu/Source/mystic/mysticpaste-react-go:/home